//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NQuery {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NQuery.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform aggregate function &apos;{1}&apos; on an expression containing an aggregate (&apos;{2}&apos;): {0}..
        /// </summary>
        internal static string AggregateCannotContainAggregate {
            get {
                return ResourceManager.GetString("AggregateCannotContainAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform aggregate function on an expression containing a subquery: {0}..
        /// </summary>
        internal static string AggregateCannotContainSubquery {
            get {
                return ResourceManager.GetString("AggregateCannotContainSubquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple columns are specified in aggregated expression &apos;{0}&apos; containing an outer reference. If an expression being aggregated contains an outer reference, then that outer reference must be the only column referenced in the expression..
        /// </summary>
        internal static string AggregateContainsColumnsFromDifferentQueries {
            get {
                return ResourceManager.GetString("AggregateContainsColumnsFromDifferentQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aggregate operation &apos;{0}&apos; cannot take a &apos;{1}&apos; data type as an argument..
        /// </summary>
        internal static string AggregateDoesNotSupportType {
            get {
                return ResourceManager.GetString("AggregateDoesNotSupportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use an aggregate or a subquery in an expression used for the group by list of a GROUP BY clause..
        /// </summary>
        internal static string AggregateInGroupBy {
            get {
                return ResourceManager.GetString("AggregateInGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An aggregate cannot appear in an ON clause unless it is in a subquery contained in a HAVING clause or select list, and the column being aggregated is an outer reference..
        /// </summary>
        internal static string AggregateInOn {
            get {
                return ResourceManager.GetString("AggregateInOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation expression &apos;{0}&apos; not valid in this context..
        /// </summary>
        internal static string AggregateInvalidInCurrentContext {
            get {
                return ResourceManager.GetString("AggregateInvalidInCurrentContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An aggregate may not appear in the WHERE clause unless it is in a subquery contained in a HAVING clause or a select list, and the column being aggregated is an outer reference..
        /// </summary>
        internal static string AggregateInWhere {
            get {
                return ResourceManager.GetString("AggregateInWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All columns in &apos;{0}&apos; must belong to the same table..
        /// </summary>
        internal static string AllColumnsMustBelongToSameTable {
            get {
                return ResourceManager.GetString("AllColumnsMustBelongToSameTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate name {0} is ambiguous between {1}..
        /// </summary>
        internal static string AmbiguousAggregate {
            get {
                return ResourceManager.GetString("AmbiguousAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operator &apos;{0}&apos; invocation on types &apos;{1}&apos; and &apos;{2}&apos; is ambiguous between method &apos;{3}&apos; and &apos;{4}&apos;..
        /// </summary>
        internal static string AmbiguousBinaryOperator {
            get {
                return ResourceManager.GetString("AmbiguousBinaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} operator is ambiguous between &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string AmbiguousCastingOperator {
            get {
                return ResourceManager.GetString("AmbiguousCastingOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column ref name {0} is ambiguous between {1}..
        /// </summary>
        internal static string AmbiguousColumnRef {
            get {
                return ResourceManager.GetString("AmbiguousColumnRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant name {0} is ambiguous between {1}..
        /// </summary>
        internal static string AmbiguousConstant {
            get {
                return ResourceManager.GetString("AmbiguousConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocation with argument types &apos;{2}&apos; is ambiguous between &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        internal static string AmbiguousInvocation {
            get {
                return ResourceManager.GetString("AmbiguousInvocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocation is ambiguous between &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        internal static string AmbiguousInvocationNoArgs {
            get {
                return ResourceManager.GetString("AmbiguousInvocationNoArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to user defined operator &apos;{0}&apos; on types &apos;{1}&apos; and &apos;{2}&apos; is ambiguous..
        /// </summary>
        internal static string AmbiguousOperatorOverloading {
            get {
                return ResourceManager.GetString("AmbiguousOperatorOverloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name {0} is ambiguous between {1}..
        /// </summary>
        internal static string AmbiguousParameter {
            get {
                return ResourceManager.GetString("AmbiguousParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name {0} is ambiguous between {1}..
        /// </summary>
        internal static string AmbiguousProperty {
            get {
                return ResourceManager.GetString("AmbiguousProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; is ambiguous between &apos;{1}&apos;..
        /// </summary>
        internal static string AmbiguousReference {
            get {
                return ResourceManager.GetString("AmbiguousReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name {0} is ambiguous between {1}..
        /// </summary>
        internal static string AmbiguousTable {
            get {
                return ResourceManager.GetString("AmbiguousTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table ref name {0} is ambiguous between {1}..
        /// </summary>
        internal static string AmbiguousTableRef {
            get {
                return ResourceManager.GetString("AmbiguousTableRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type reference &apos;{0}&apos; is ambiguous between 1}..
        /// </summary>
        internal static string AmbiguousType {
            get {
                return ResourceManager.GetString("AmbiguousType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary operator &apos;{0}&apos; invocation on type &apos;{1}&apos; is ambiguous between method &apos;{2}&apos; and &apos;{3}&apos;..
        /// </summary>
        internal static string AmbiguousUnaryOp {
            get {
                return ResourceManager.GetString("AmbiguousUnaryOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of type &apos;{0}&apos;..
        /// </summary>
        internal static string ArgMustBeOfType {
            get {
                return ResourceManager.GetString("ArgMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array argument &apos;{0}&apos; must have same size as &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentArrayMustHaveSameSize {
            get {
                return ResourceManager.GetString("ArgumentArrayMustHaveSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array must not be empty..
        /// </summary>
        internal static string ArgumentArrayMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentArrayMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; is out-of-range ({2}-{3}), actual value was {1}..
        /// </summary>
        internal static string ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation modifier &apos;*&apos; not allowed in function call &apos;{0}&apos;..
        /// </summary>
        internal static string AsteriskModifierNotAllowed {
            get {
                return ResourceManager.GetString("AsteriskModifierNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operator &apos;{0} {1} {2}&apos; threw an exception: {6}{7}Operator method: &apos;{3}&apos;. Arguments: &apos;{4}&apos;, &apos;{5}&apos;..
        /// </summary>
        internal static string BinaryOperatorFailed {
            get {
                return ResourceManager.GetString("BinaryOperatorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A binding with the same name &apos;{0}&apos; already exists in this collection..
        /// </summary>
        internal static string BindingWithSameNameAlreadyInCollection {
            get {
                return ResourceManager.GetString("BindingWithSameNameAlreadyInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply binary operator &apos;{0}&apos; on types &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string CannotApplyBinaryOp {
            get {
                return ResourceManager.GetString("CannotApplyBinaryOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply unary operator &apos;{0}&apos; on type &apos;{1}&apos;..
        /// </summary>
        internal static string CannotApplyUnaryOp {
            get {
                return ResourceManager.GetString("CannotApplyUnaryOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast &apos;{0}&apos; from &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string CannotCast {
            get {
                return ResourceManager.GetString("CannotCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot evaluate constant expression: {0}.
        /// </summary>
        internal static string CannotFoldConstants {
            get {
                return ResourceManager.GetString("CannotFoldConstants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load assembly &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string CannotLoadTypeAssembly {
            get {
                return ResourceManager.GetString("CannotLoadTypeAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casting operator threw an exception..
        /// </summary>
        internal static string CastingOperatorFailed {
            get {
                return ResourceManager.GetString("CastingOperatorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child column &apos;{0}&apos; in table &apos;{1}&apos; not found..
        /// </summary>
        internal static string ChildColumnNotFound {
            get {
                return ResourceManager.GetString("ChildColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to childColumns must not contain columns of different tables..
        /// </summary>
        internal static string ChildColumnsMustNotContainColumnsOfOtherTables {
            get {
                return ResourceManager.GetString("ChildColumnsMustNotContainColumnsOfOtherTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child table must exist in data context..
        /// </summary>
        internal static string ChildTableMustExistInDataContext {
            get {
                return ResourceManager.GetString("ChildTableMustExistInDataContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot provide code assistance: {0}.
        /// </summary>
        internal static string CodeAssistanceFailed {
            get {
                return ResourceManager.GetString("CodeAssistanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnBinding.GetValue() threw an exception..
        /// </summary>
        internal static string ColumnBindingGetValueFailed {
            get {
                return ResourceManager.GetString("ColumnBindingGetValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstantBinding.GetValue() threw an exception..
        /// </summary>
        internal static string ConstantBindingGetValueFailed {
            get {
                return ResourceManager.GetString("ConstantBindingGetValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A constant expression was encountered in the ORDER BY list..
        /// </summary>
        internal static string ConstantExpressionInOrderBy {
            get {
                return ResourceManager.GetString("ConstantExpressionInOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion of {0} to {1} failed: {2}.
        /// </summary>
        internal static string ConversionFailed {
            get {
                return ResourceManager.GetString("ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTINCT operator is not allowed in the recursive part of a recursive common table expression &apos;{0}&apos;..
        /// </summary>
        internal static string CteContainsDistinct {
            get {
                return ResourceManager.GetString("CteContainsDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP BY, HAVING, or aggregate functions are not allowed in the recursive part of a recursive common table expression &apos;{0}&apos;..
        /// </summary>
        internal static string CteContainsGroupByHavingOrAggregate {
            get {
                return ResourceManager.GetString("CteContainsGroupByHavingOrAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive member of a common table expression &apos;{0}&apos; has multiple recursive references..
        /// </summary>
        internal static string CteContainsMultipleRecursiveReferences {
            get {
                return ResourceManager.GetString("CteContainsMultipleRecursiveReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer join is not allowed in the recursive part of a recursive common table expression &apos;{0}&apos;..
        /// </summary>
        internal static string CteContainsOuterJoin {
            get {
                return ResourceManager.GetString("CteContainsOuterJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive references are not allowed in subqueries.
        /// </summary>
        internal static string CteContainsRecursiveReferenceInSubquery {
            get {
                return ResourceManager.GetString("CteContainsRecursiveReferenceInSubquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP operator is not allowed in the recursive part of a recursive common table expression &apos;{0}&apos;..
        /// </summary>
        internal static string CteContainsTop {
            get {
                return ResourceManager.GetString("CteContainsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An anchor member was found in the recursive part of recursive query &apos;{0}&apos;..
        /// </summary>
        internal static string CteContainsUnexpectedAnchorMember {
            get {
                return ResourceManager.GetString("CteContainsUnexpectedAnchorMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNION operator is not allowed in the recursive part of a recursive common table expression &apos;{0}&apos;..
        /// </summary>
        internal static string CteContainsUnion {
            get {
                return ResourceManager.GetString("CteContainsUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No anchor member was specified for recursive query &apos;{0}&apos;..
        /// </summary>
        internal static string CteDoesNotHaveAnchorMember {
            get {
                return ResourceManager.GetString("CteDoesNotHaveAnchorMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive common table expression &apos;{0}&apos; does not contain a top-level UNION ALL operator..
        /// </summary>
        internal static string CteDoesNotHaveUnionAll {
            get {
                return ResourceManager.GetString("CteDoesNotHaveUnionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column &apos;{0}&apos; was specified multiple times for &apos;{1}&apos;..
        /// </summary>
        internal static string CteHasDuplicateColumnName {
            get {
                return ResourceManager.GetString("CteHasDuplicateColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate common table expression name &apos;{0}&apos; was specified..
        /// </summary>
        internal static string CteHasDuplicateTableName {
            get {
                return ResourceManager.GetString("CteHasDuplicateTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has fewer columns than were specified in the column list..
        /// </summary>
        internal static string CteHasFewerColumnsThanSpecified {
            get {
                return ResourceManager.GetString("CteHasFewerColumnsThanSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has more columns than were specified in the column list..
        /// </summary>
        internal static string CteHasMoreColumnsThanSpecified {
            get {
                return ResourceManager.GetString("CteHasMoreColumnsThanSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types don&apos;t match between the anchor and the recursive part in column &apos;{0}&apos; of recursive query &apos;{1}&apos;..
        /// </summary>
        internal static string CteHasTypeMismatchBetweenAnchorAndRecursivePart {
            get {
                return ResourceManager.GetString("CteHasTypeMismatchBetweenAnchorAndRecursivePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All queries combined using a UNION, INTERSECT or EXCEPT operator must have an equal number of expressions in their target lists..
        /// </summary>
        internal static string DifferentExpressionCountInBinaryQuery {
            get {
                return ResourceManager.GetString("DifferentExpressionCountInBinaryQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate function named &apos;{0}&apos; already in list..
        /// </summary>
        internal static string DuplicateAggregate {
            get {
                return ResourceManager.GetString("DuplicateAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function {0} already declared..
        /// </summary>
        internal static string DuplicateFunction {
            get {
                return ResourceManager.GetString("DuplicateFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property collection already contains a property named &apos;{0}&apos;..
        /// </summary>
        internal static string DuplicatePropertyReference {
            get {
                return ResourceManager.GetString("DuplicatePropertyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the relation {0} is already a data gatherer registered..
        /// </summary>
        internal static string DuplicateRelationDataGatherer {
            get {
                return ResourceManager.GetString("DuplicateRelationDataGatherer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The correlation name &apos;{0}&apos; is specified multiple times in a FROM clause..
        /// </summary>
        internal static string DuplicateTableRefInFrom {
            get {
                return ResourceManager.GetString("DuplicateTableRefInFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression could not be compiled.{0}.
        /// </summary>
        internal static string ExpressionCompilationFailed {
            get {
                return ResourceManager.GetString("ExpressionCompilationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionBinding.Invoke() threw an exception..
        /// </summary>
        internal static string FunctionBindingInvokeFailed {
            get {
                return ResourceManager.GetString("FunctionBindingInvokeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function must return a value..
        /// </summary>
        internal static string FunctionMustNotBeVoid {
            get {
                return ResourceManager.GetString("FunctionMustNotBeVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions with array parameters are not supported..
        /// </summary>
        internal static string FunctionMustNotHaveArrayParams {
            get {
                return ResourceManager.GetString("FunctionMustNotHaveArrayParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions with optional parameters are not supported..
        /// </summary>
        internal static string FunctionMustNotHaveOptionalParams {
            get {
                return ResourceManager.GetString("FunctionMustNotHaveOptionalParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions with out or ref parameters are not supported..
        /// </summary>
        internal static string FunctionMustNotHaveRefOrOutParams {
            get {
                return ResourceManager.GetString("FunctionMustNotHaveRefOrOutParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A function with the same name and signature already exists: {0}.
        /// </summary>
        internal static string FunctionWithSameNameAndSignatureAlreadyInCollection {
            get {
                return ResourceManager.GetString("FunctionWithSameNameAndSignatureAlreadyInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each GROUP BY expression must contain at least one column that is not an outer reference..
        /// </summary>
        internal static string GroupByItemDoesNotReferenceAnyColumns {
            get {
                return ResourceManager.GetString("GroupByItemDoesNotReferenceAnyColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAVING clause must evaluate to BOOLEAN expression..
        /// </summary>
        internal static string HavingClauseMustEvaluateToBool {
            get {
                return ResourceManager.GetString("HavingClauseMustEvaluateToBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; is invalid in the HAVING clause because it is not contained in either an aggregate function or the GROUP BY clause..
        /// </summary>
        internal static string HavingExpressionNotAggregatedOrGrouped {
            get {
                return ResourceManager.GetString("HavingExpressionNotAggregatedOrGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAggregator.Accumulate() threw an exception..
        /// </summary>
        internal static string IAggregatorAccumulateFailed {
            get {
                return ResourceManager.GetString("IAggregatorAccumulateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAggregator.Init() threw an exception..
        /// </summary>
        internal static string IAggregatorInitFailed {
            get {
                return ResourceManager.GetString("IAggregatorInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAggregator.Terminate() threw an exception..
        /// </summary>
        internal static string IAggregatorTerminateFailed {
            get {
                return ResourceManager.GetString("IAggregatorTerminateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in input &apos;{0}&apos;..
        /// </summary>
        internal static string IllegalInputCharacter {
            get {
                return ResourceManager.GetString("IllegalInputCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMethodProvider.GetMethods() threw an exception..
        /// </summary>
        internal static string IMethodProviderGetMethodsFailed {
            get {
                return ResourceManager.GetString("IMethodProviderGetMethodsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error: {0}.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.GetValue() not supported..
        /// </summary>
        internal static string InternalErrorGetValueNotSupported {
            get {
                return ResourceManager.GetString("InternalErrorGetValueNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to read when no data is present..
        /// </summary>
        internal static string InvalidAttemptToRead {
            get {
                return ResourceManager.GetString("InvalidAttemptToRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid binary number..
        /// </summary>
        internal static string InvalidBinary {
            get {
                return ResourceManager.GetString("InvalidBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid binary operator: &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidBinaryOperator {
            get {
                return ResourceManager.GetString("InvalidBinaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data type &apos;{0}&apos; cannot be used in GROUP BY since it cannot be compared or sorted..
        /// </summary>
        internal static string InvalidDataTypeInGroupBy {
            get {
                return ResourceManager.GetString("InvalidDataTypeInGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data type &apos;{0}&apos; cannot be used in ORDER BY since it cannot be compared or sorted..
        /// </summary>
        internal static string InvalidDataTypeInOrderBy {
            get {
                return ResourceManager.GetString("InvalidDataTypeInOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data type &apos;{0}&apos; cannot be used in SELECT DISTINCT since it cannot be compared or sorted..
        /// </summary>
        internal static string InvalidDataTypeInSelectDistinct {
            get {
                return ResourceManager.GetString("InvalidDataTypeInSelectDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data type &apos;{0}&apos; cannot be used in {1} since it cannot be compared or sorted..
        /// </summary>
        internal static string InvalidDataTypeInUnion {
            get {
                return ResourceManager.GetString("InvalidDataTypeInUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid date..
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid decimal number..
        /// </summary>
        internal static string InvalidDecimal {
            get {
                return ResourceManager.GetString("InvalidDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid hex number..
        /// </summary>
        internal static string InvalidHex {
            get {
                return ResourceManager.GetString("InvalidHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text &apos;{0}&apos; is not a valid identifier.
        /// </summary>
        internal static string InvalidIdentifier {
            get {
                return ResourceManager.GetString("InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid integer..
        /// </summary>
        internal static string InvalidInteger {
            get {
                return ResourceManager.GetString("InvalidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid octal number..
        /// </summary>
        internal static string InvalidOctal {
            get {
                return ResourceManager.GetString("InvalidOctal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOME, ANY and ALL can only be applied on =, &lt;&gt;, &lt;, &lt;=, &gt;, or &gt;=.
        /// </summary>
        internal static string InvalidOperatorForAllAny {
            get {
                return ResourceManager.GetString("InvalidOperatorForAllAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row reference &apos;{0}&apos; is not valid since the table it is referring to is either a derived table or a common table expression (CTE)..
        /// </summary>
        internal static string InvalidRowReference {
            get {
                return ResourceManager.GetString("InvalidRowReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type reference {0} is malformed. Neither quoted nor parenthesized identifiers can be used in type references. Use string literals to express case sensitivity..
        /// </summary>
        internal static string InvalidTypeReference {
            get {
                return ResourceManager.GetString("InvalidTypeReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operator: &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidUnaryOperator {
            get {
                return ResourceManager.GetString("InvalidUnaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocation of &apos;{0}&apos; requires parentheses..
        /// </summary>
        internal static string InvocationRequiresParentheses {
            get {
                return ResourceManager.GetString("InvocationRequiresParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPropertyProvider.GetProperties() threw an exception..
        /// </summary>
        internal static string IPropertyProviderGetPropertiesFailed {
            get {
                return ResourceManager.GetString("IPropertyProviderGetPropertiesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum recursion 100 has been exhausted before statement completion..
        /// </summary>
        internal static string MaximumRecursionLevelExceeded {
            get {
                return ResourceManager.GetString("MaximumRecursionLevelExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodBinding.Invoke() threw an exception..
        /// </summary>
        internal static string MethodBindingInvokeFailed {
            get {
                return ResourceManager.GetString("MethodBindingInvokeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add properties -- no property provider is registered for type &apos;{0}&apos;..
        /// </summary>
        internal static string MissingPropertyProvider {
            get {
                return ResourceManager.GetString("MissingPropertyProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add table -- no table provider is registered for type &apos;{0}&apos;..
        /// </summary>
        internal static string MissingTableProvider {
            get {
                return ResourceManager.GetString("MissingTableProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify table to select from..
        /// </summary>
        internal static string MustSpecifyTableToSelectFrom {
            get {
                return ResourceManager.GetString("MustSpecifyTableToSelectFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No column name was specified for column {0} of &apos;{1}&apos;..
        /// </summary>
        internal static string NoColumnAliasSpecified {
            get {
                return ResourceManager.GetString("NoColumnAliasSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No property provider is registered for type &apos;{0}&apos; and there is no default property provider..
        /// </summary>
        internal static string NoPropertyProviderRegisteredAndDefaultProviderIsMissing {
            get {
                return ResourceManager.GetString("NoPropertyProviderRegisteredAndDefaultProviderIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number &apos;{0}&apos; is too large..
        /// </summary>
        internal static string NumberTooLarge {
            get {
                return ResourceManager.GetString("NumberTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ORDER BY position number {0} is out of range of the number of items in the select list..
        /// </summary>
        internal static string OrderByColumnPositionIsOutOfRange {
            get {
                return ResourceManager.GetString("OrderByColumnPositionIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; is invalid in the ORDER BY clause because it is not contained in an aggregate function and there is no GROUP BY clause..
        /// </summary>
        internal static string OrderByExpressionNotAggregatedAndNoGroupBy {
            get {
                return ResourceManager.GetString("OrderByExpressionNotAggregatedAndNoGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause..
        /// </summary>
        internal static string OrderByExpressionNotAggregatedOrGrouped {
            get {
                return ResourceManager.GetString("OrderByExpressionNotAggregatedOrGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ORDER BY clause is invalid in derived tables, subqueries, and common table expressions, unless TOP is also specified..
        /// </summary>
        internal static string OrderByInvalidInSubqueryUnlessTopIsAlsoSpecified {
            get {
                return ResourceManager.GetString("OrderByInvalidInSubqueryUnlessTopIsAlsoSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BY items must appear in the select list if SELECT DISTINCT is specified..
        /// </summary>
        internal static string OrderByItemsMustBeInSelectListIfDistinctSpecified {
            get {
                return ResourceManager.GetString("OrderByItemsMustBeInSelectListIfDistinctSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BY items must appear in the select list if the statement contains a UNION, INTERSECT or EXCEPT operator..
        /// </summary>
        internal static string OrderByItemsMustBeInSelectListIfUnionSpecified {
            get {
                return ResourceManager.GetString("OrderByItemsMustBeInSelectListIfUnionSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterBinding.Value threw an exception..
        /// </summary>
        internal static string ParameterBindingGetValueFailed {
            get {
                return ResourceManager.GetString("ParameterBindingGetValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter type is not assignable from the given value..
        /// </summary>
        internal static string ParameterValueTypeMismatch {
            get {
                return ResourceManager.GetString("ParameterValueTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent column &apos;{0}&apos; in table &apos;{1}&apos; not found..
        /// </summary>
        internal static string ParentColumnNotFound {
            get {
                return ResourceManager.GetString("ParentColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parentColumns must contain at least one column..
        /// </summary>
        internal static string ParentColumnsMustContainAtLeastOneColumn {
            get {
                return ResourceManager.GetString("ParentColumnsMustContainAtLeastOneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to childColumns.Length must match parentColumns.Length..
        /// </summary>
        internal static string ParentColumnsMustHaveSameSizeAsChildColumns {
            get {
                return ResourceManager.GetString("ParentColumnsMustHaveSameSizeAsChildColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parentColumns must not contain columns of different tables..
        /// </summary>
        internal static string ParentColumnsMustNotContainColumnsOfOtherTables {
            get {
                return ResourceManager.GetString("ParentColumnsMustNotContainColumnsOfOtherTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent table must exist in data context..
        /// </summary>
        internal static string ParentTableMustExistInDataContext {
            get {
                return ResourceManager.GetString("ParentTableMustExistInDataContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyBinding.GetValue() threw an exception..
        /// </summary>
        internal static string PropertyBindingGetValueFailed {
            get {
                return ResourceManager.GetString("PropertyBindingGetValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property has not been initialized..
        /// </summary>
        internal static string PropertyNotInitialized {
            get {
                return ResourceManager.GetString("PropertyNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query could not be compiled.{0}.
        /// </summary>
        internal static string QueryCompilationFailed {
            get {
                return ResourceManager.GetString("QueryCompilationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; is invalid in the select list because it is not contained in an aggregate function and there is no GROUP BY clause..
        /// </summary>
        internal static string SelectExpressionNotAggregatedAndNoGroupBy {
            get {
                return ResourceManager.GetString("SelectExpressionNotAggregatedAndNoGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause..
        /// </summary>
        internal static string SelectExpressionNotAggregatedOrGrouped {
            get {
                return ResourceManager.GetString("SelectExpressionNotAggregatedOrGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Plan Element.
        /// </summary>
        internal static string ShowPlanElemenClassName {
            get {
                return ResourceManager.GetString("ShowPlanElemenClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined Values.
        /// </summary>
        internal static string ShowPlanGroupDefinedValues {
            get {
                return ResourceManager.GetString("ShowPlanGroupDefinedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By.
        /// </summary>
        internal static string ShowPlanGroupGroupBy {
            get {
                return ResourceManager.GetString("ShowPlanGroupGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order By.
        /// </summary>
        internal static string ShowPlanGroupOrderBy {
            get {
                return ResourceManager.GetString("ShowPlanGroupOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer References.
        /// </summary>
        internal static string ShowPlanGroupOuterReferences {
            get {
                return ResourceManager.GetString("ShowPlanGroupOuterReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output List.
        /// </summary>
        internal static string ShowPlanGroupOutputList {
            get {
                return ResourceManager.GetString("ShowPlanGroupOutputList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string ShowPlanGroupStatistics {
            get {
                return ResourceManager.GetString("ShowPlanGroupStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie Columns.
        /// </summary>
        internal static string ShowPlanGroupTieColumns {
            get {
                return ResourceManager.GetString("ShowPlanGroupTieColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string ShowPlanKeyColumn {
            get {
                return ResourceManager.GetString("ShowPlanKeyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType.
        /// </summary>
        internal static string ShowPlanKeyDataType {
            get {
                return ResourceManager.GetString("ShowPlanKeyDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string ShowPlanKeyEmpty {
            get {
                return ResourceManager.GetString("ShowPlanKeyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Keys Build.
        /// </summary>
        internal static string ShowPlanKeyHashKeysBuild {
            get {
                return ResourceManager.GetString("ShowPlanKeyHashKeysBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Keys Probe.
        /// </summary>
        internal static string ShowPlanKeyHashKeysProbe {
            get {
                return ResourceManager.GetString("ShowPlanKeyHashKeysProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string ShowPlanKeyIndex {
            get {
                return ResourceManager.GetString("ShowPlanKeyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        internal static string ShowPlanKeyLimit {
            get {
                return ResourceManager.GetString("ShowPlanKeyLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Operator.
        /// </summary>
        internal static string ShowPlanKeyLogicalOperator {
            get {
                return ResourceManager.GetString("ShowPlanKeyLogicalOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string ShowPlanKeyOrder {
            get {
                return ResourceManager.GetString("ShowPlanKeyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Name.
        /// </summary>
        internal static string ShowPlanKeyOutputName {
            get {
                return ResourceManager.GetString("ShowPlanKeyOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passthru.
        /// </summary>
        internal static string ShowPlanKeyPassthru {
            get {
                return ResourceManager.GetString("ShowPlanKeyPassthru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate.
        /// </summary>
        internal static string ShowPlanKeyPredicate {
            get {
                return ResourceManager.GetString("ShowPlanKeyPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe.
        /// </summary>
        internal static string ShowPlanKeyProbe {
            get {
                return ResourceManager.GetString("ShowPlanKeyProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Column.
        /// </summary>
        internal static string ShowPlanKeyProbeColumn {
            get {
                return ResourceManager.GetString("ShowPlanKeyProbeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Residual.
        /// </summary>
        internal static string ShowPlanKeyProbeResidual {
            get {
                return ResourceManager.GetString("ShowPlanKeyProbeResidual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string ShowPlanKeySource {
            get {
                return ResourceManager.GetString("ShowPlanKeySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Row Count.
        /// </summary>
        internal static string ShowPlanKeyStatisticsAverageRowCount {
            get {
                return ResourceManager.GetString("ShowPlanKeyStatisticsAverageRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Count.
        /// </summary>
        internal static string ShowPlanKeyStatisticsOpenCount {
            get {
                return ResourceManager.GetString("ShowPlanKeyStatisticsOpenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Count.
        /// </summary>
        internal static string ShowPlanKeyStatisticsRowCount {
            get {
                return ResourceManager.GetString("ShowPlanKeyStatisticsRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string ShowPlanKeyTable {
            get {
                return ResourceManager.GetString("ShowPlanKeyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string ShowPlanKeyTarget {
            get {
                return ResourceManager.GetString("ShowPlanKeyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string ShowPlanKeyWarning {
            get {
                return ResourceManager.GetString("ShowPlanKeyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Stack.
        /// </summary>
        internal static string ShowPlanKeyWithStack {
            get {
                return ResourceManager.GetString("ShowPlanKeyWithStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Ties.
        /// </summary>
        internal static string ShowPlanKeyWithTies {
            get {
                return ResourceManager.GetString("ShowPlanKeyWithTies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinct Sort.
        /// </summary>
        internal static string ShowPlanLogicalOperatorDistinctSort {
            get {
                return ResourceManager.GetString("ShowPlanLogicalOperatorDistinctSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eager Spool.
        /// </summary>
        internal static string ShowPlanLogicalOperatorEagerSpool {
            get {
                return ResourceManager.GetString("ShowPlanLogicalOperatorEagerSpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Outer Join.
        /// </summary>
        internal static string ShowPlanLogicalOperatorFullOuterJoin {
            get {
                return ResourceManager.GetString("ShowPlanLogicalOperatorFullOuterJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Join.
        /// </summary>
        internal static string ShowPlanLogicalOperatorInnerJoin {
            get {
                return ResourceManager.GetString("ShowPlanLogicalOperatorInnerJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lazy Spool.
        /// </summary>
        internal static string ShowPlanLogicalOperatorLazySpool {
            get {
                return ResourceManager.GetString("ShowPlanLogicalOperatorLazySpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Anti Semi Join.
        /// </summary>
        internal static string ShowPlanLogicalOperatorLeftAntiSemiJoin {
            get {
                return ResourceManager.GetString("ShowPlanLogicalOperatorLeftAntiSemiJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Outer Join.
        /// </summary>
        internal static string ShowPlanLogicalOperatorLeftOuterJoin {
            get {
                return ResourceManager.GetString("ShowPlanLogicalOperatorLeftOuterJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Semi Join.
        /// </summary>
        internal static string ShowPlanLogicalOperatorLeftSemiJoin {
            get {
                return ResourceManager.GetString("ShowPlanLogicalOperatorLeftSemiJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Anti Semi Join.
        /// </summary>
        internal static string ShowPlanLogicalOperatorRightAntiSemiJoin {
            get {
                return ResourceManager.GetString("ShowPlanLogicalOperatorRightAntiSemiJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Outer Join.
        /// </summary>
        internal static string ShowPlanLogicalOperatorRightOuterJoin {
            get {
                return ResourceManager.GetString("ShowPlanLogicalOperatorRightOuterJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Semi Join.
        /// </summary>
        internal static string ShowPlanLogicalOperatorRightSemiJoin {
            get {
                return ResourceManager.GetString("ShowPlanLogicalOperatorRightSemiJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string ShowPlanLogicalOperatorSort {
            get {
                return ResourceManager.GetString("ShowPlanLogicalOperatorSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASC.
        /// </summary>
        internal static string ShowPlanSortOrderAscending {
            get {
                return ResourceManager.GetString("ShowPlanSortOrderAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESC.
        /// </summary>
        internal static string ShowPlanSortOrderDescending {
            get {
                return ResourceManager.GetString("ShowPlanSortOrderDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No join predicate.
        /// </summary>
        internal static string ShowPlanWarningNoJoinPredicate {
            get {
                return ResourceManager.GetString("ShowPlanWarningNoJoinPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found &apos;{0}&apos; but &apos;&lt;Expression&gt;&apos; expected..
        /// </summary>
        internal static string SimpleExpressionExpected {
            get {
                return ResourceManager.GetString("SimpleExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, &lt;, &lt;= , &gt;, &gt;= or when the subquery is used as an expression..
        /// </summary>
        internal static string SubqueryReturnedMoreThanRow {
            get {
                return ResourceManager.GetString("SubqueryReturnedMoreThanRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A table must have at least one column..
        /// </summary>
        internal static string TableMustHaveAtLeastOneColumn {
            get {
                return ResourceManager.GetString("TableMustHaveAtLeastOneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A table provider for type &apos;{0}&apos; has already been assigned..
        /// </summary>
        internal static string TableProviderAlreadyRegistered {
            get {
                return ResourceManager.GetString("TableProviderAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found &apos;{0}&apos; but &apos;&lt;Table Reference&gt;&apos; expected.
        /// </summary>
        internal static string TableReferenceExpected {
            get {
                return ResourceManager.GetString("TableReferenceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}: {1}&apos; is introduced in a different branch within the join hierarchy and is therefore inaccessible..
        /// </summary>
        internal static string TableRefInaccessible {
            get {
                return ResourceManager.GetString("TableRefInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot narrow down the target type to &apos;{1}&apos; since the static expression type &apos;{0}&apos; would not be assignable from the new target type &apos;{1}&apos; anymore..
        /// </summary>
        internal static string TargetTypeMismatch {
            get {
                return ResourceManager.GetString("TargetTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Date Literal&gt;.
        /// </summary>
        internal static string TokenDateLiteral {
            get {
                return ResourceManager.GetString("TokenDateLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;End-of-File&gt;.
        /// </summary>
        internal static string TokenEndOfFile {
            get {
                return ResourceManager.GetString("TokenEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found &apos;{0}&apos; but expected &apos;{1}&apos;..
        /// </summary>
        internal static string TokenExpected {
            get {
                return ResourceManager.GetString("TokenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Identifier&gt;.
        /// </summary>
        internal static string TokenIdentifier {
            get {
                return ResourceManager.GetString("TokenIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Number Literal&gt;.
        /// </summary>
        internal static string TokenNumberLiteral {
            get {
                return ResourceManager.GetString("TokenNumberLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;String Literal&gt;.
        /// </summary>
        internal static string TokenStringLiteral {
            get {
                return ResourceManager.GetString("TokenStringLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown&gt;.
        /// </summary>
        internal static string TokenUnknown {
            get {
                return ResourceManager.GetString("TokenUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one expression can be specified in the select list when the subquery is not introduced with EXISTS..
        /// </summary>
        internal static string TooManyExpressionsInSelectListOfSubquery {
            get {
                return ResourceManager.GetString("TooManyExpressionsInSelectListOfSubquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TOP N WITH TIES clause is not allowed without a corresponding ORDER BY clause..
        /// </summary>
        internal static string TopWithTiesRequiresOrderBy {
            get {
                return ResourceManager.GetString("TopWithTiesRequiresOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is already registered..
        /// </summary>
        internal static string TypeAlreadyRegistered {
            get {
                return ResourceManager.GetString("TypeAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary operator &apos;{0} {1}&apos; threw an exception: {3}{5}Operator method: &apos;{2}&apos;. Argument: &apos;{4}&apos;..
        /// </summary>
        internal static string UnaryOperatorFailed {
            get {
                return ResourceManager.GetString("UnaryOperatorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{1}&apos; not declared in table &apos;{0}&apos;..
        /// </summary>
        internal static string UndeclaredColumn {
            get {
                return ResourceManager.GetString("UndeclaredColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier &apos;{0}&apos; does not refer to a column, table or property..
        /// </summary>
        internal static string UndeclaredEntity {
            get {
                return ResourceManager.GetString("UndeclaredEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}({1})&apos; is not declared..
        /// </summary>
        internal static string UndeclaredFunction {
            get {
                return ResourceManager.GetString("UndeclaredFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not have a method &apos;{1}({2})&apos;..
        /// </summary>
        internal static string UndeclaredMethod {
            get {
                return ResourceManager.GetString("UndeclaredMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is not declared..
        /// </summary>
        internal static string UndeclaredParameter {
            get {
                return ResourceManager.GetString("UndeclaredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not have a property &apos;{1}&apos;..
        /// </summary>
        internal static string UndeclaredProperty {
            get {
                return ResourceManager.GetString("UndeclaredProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; is not declared..
        /// </summary>
        internal static string UndeclaredTable {
            get {
                return ResourceManager.GetString("UndeclaredTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve type: {0}.
        /// </summary>
        internal static string UndeclaredType {
            get {
                return ResourceManager.GetString("UndeclaredType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled case label: {0}.
        /// </summary>
        internal static string UnhandledCaseLabel {
            get {
                return ResourceManager.GetString("UnhandledCaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error {0}..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment &apos;{0}&apos; is not properly terminated..
        /// </summary>
        internal static string UnterminatedComment {
            get {
                return ResourceManager.GetString("UnterminatedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &apos;{0}&apos; is not properly terminated..
        /// </summary>
        internal static string UnterminatedDate {
            get {
                return ResourceManager.GetString("UnterminatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parenthesized identifier &apos;{0}&apos; is not properly terminated..
        /// </summary>
        internal static string UnterminatedParenthesizedIdentifier {
            get {
                return ResourceManager.GetString("UnterminatedParenthesizedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quoted identifier &apos;{0}&apos; is not properly terminated..
        /// </summary>
        internal static string UnterminatedQuotedIdentifier {
            get {
                return ResourceManager.GetString("UnterminatedQuotedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; is not properly terminated..
        /// </summary>
        internal static string UnterminatedString {
            get {
                return ResourceManager.GetString("UnterminatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHEN expression &apos;{0}&apos; must evaluate to &apos;{1}&apos; if CASE input expression is omitted..
        /// </summary>
        internal static string WhenMustEvaluateToBoolIfCaseInputIsOmitted {
            get {
                return ResourceManager.GetString("WhenMustEvaluateToBoolIfCaseInputIsOmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHERE clause must evaluate to BOOLEAN expression..
        /// </summary>
        internal static string WhereClauseMustEvaluateToBool {
            get {
                return ResourceManager.GetString("WhereClauseMustEvaluateToBool", resourceCulture);
            }
        }
    }
}
